# Generated by Django 3.0 on 2020-04-18 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed Sending', 'Failed Sending')], default='Pending', max_length=256)),
                ('subject', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('priority', models.IntegerField(null=True)),
                ('attachment', models.FileField(upload_to='')),
                ('recipients', models.ManyToManyField(related_name='_email_recipients_+', to='api.Recipient')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emails_sent', to='api.Recipient')),
            ],
        ),
    ]
