name: Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare project
      run: |
        cp .env.template .env
        docker-compose build
        docker-compose run backend python manage.py migrate
    - name: Run tests
      run: docker-compose run backend python manage.py test
    - name: Run linter
      run: docker-compose run backend flake8

